name: acs730workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "hello world!"
      - name: print end
        run: echo "end of the file"
